# creating a network for the database
services:
  portoturismo_mongo:
    image: mongo:5.0.9
    container_name: portoturismo_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/data/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  portoturismo_frontend:
    image: portoturismo_frontend
    container_name: portoturismo_frontend
    tty: true
    volumes:
      - ./Frontend/:/frontend/
    ports:
      - 3000:3000
    depends_on:
      - portoturismo_backend
    environment:
      REACT_APP_NG_API_HOST: http://127.0.0.1:8000
      REACT_APP_HOST: 127.0.0.1:3000
      REACT_APP_TINY_API: t7oertz17kn7nbifea1uplykssgq4ervr3lpyym6sqsi1kko
  portoturismo_backend:
    image: portoturismo_backend
    container_name: portoturismo_backend
    tty: true
    volumes:
      - ./Backend/:/backend/
    depends_on:
      - portoturismo_mongo
    ports:
      - 8000:8000
    environment:
      APP_NAME: Portoturismo
      APP_ENV: local
      APP_KEY: base64:VsV0r6QK3jmUkDza/ZRagnL3UCikzS+PD2B7zzK271U=
      DB_HOST: portoturismo_mongo
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_URI: mongodb://root:example@portoturismo_mongo:27017/
