services:
  portoturismo_mongo:
    image: mongo:5.0.9
    container_name: portoturismo_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  portoturismo_frontend:
    image: portoturismo_frontend
    container_name: portoturismo_frontend
    tty: true
    ports:
      - 3000:3000
    environment:
      REACT_APP_NG_API_HOST: http://www.localhost:8000
      REACT_APP_HOST: http://www.localhost:3000
      REACT_APP_TINY_API: t7oertz17kn7nbifea1uplykssgq4ervr3lpyym6sqsi1kko
