version: "3.7"
    
networks:
  dbnet:
    external: true
services:
  portoturismo_mysql:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=Tester
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=proyecto_turismo
      - app-tier
    networks:
      - dbnet
    ports:
      - "3306:3306"
    volumes:
      - ./Backend/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data-mysql:/var/lib/mysql
  portoturismo_mongodb:
    image: mongo:5.0.9-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data-mongo/:/data/db
    ports:
      - 27017:27017
  # portoturismo_backend:
  #   image: portoturismo_backend:latest
  #   networks:
  #     - dbnet
  #   depends_on:
  #     - portoturismo_mysql
  #     - portoturismo_mongodb
  #   restart: always
  #   environment:
  #     - DB_HOST=portoturismo_mysql
  #     - DB_USER=root
  #     - DB_PASSWORD=secret
  #     - DB_DATABASE=proyecto_turismo
  #     - MONGO_URL_CONN=mongodb://127.0.0.1:27017/
  #     - MONGO_DB_NAME=proyecto_turismo
  #     - API_HOST=%
  #     - API_PORT=8500
  #     - JWT_KEY=12345678
  #   volumes:
  #     - ./Backend:/Backend
  #   ports:
  #     - 8500:8500
  portoturismo_frontend:
    image: portoturismo_frontend:latest
    environment:
      - REACT_APP_API_HOST=http://127.0.0.1:8500
      - REACT_APP_HOST=http://127.0.0.1:3000
      - REACT_APP_TINY_API=t7oertz17kn7nbifea1uplykssgq4ervr3lpyym6sqsi1kko
    # depends_on:
    #   - portoturismo_backend
    ports:
      - 3000:3000
    volumes:
      - ./Frontend:/Frontend

